spring.application.name=notes-api

spring.security.user.name=admin
spring.security.user.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/securenotes
spring.datasource.username=postgres
spring.datasource.password=Nikhil@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect